create table arquivo_cnab (
    id BIGINT generated by default as identity NOT NULL,
    nome text,
    constraint arquivo_cnab_pk primary key (id)
);

create unique index arquivo_cnab_unq01 on arquivo_cnab (nome);

create table transacao_financeira (
  id BIGINT generated by default as identity NOT NULL,
  tipo text,
  data_transacao date,
  valor numeric(18,2),
  cpf varchar(20),
  cartao text,
  hora time,
  dono text,
  loja text,
  constraint transacao_financeira_pk primary key (id)
);

